[1m============================= test session starts ==============================[0m
platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
cachedir: build/plansys2_data_collector/.pytest_cache
rootdir: /home/kalman/plansys2_ws/src/plansys2_data_collector
plugins: ament-lint-0.16.3, ament-xmllint-0.16.3, ament-copyright-0.16.3, ament-pep257-0.16.3, launch-testing-ros-0.26.4, ament-flake8-0.16.3, launch-testing-3.4.0, anyio-4.3.0, cov-3.0.0, colcon-core-0.15.2
[1mcollecting ... [0m[1m
collected 3 items                                                              [0m

test/test_copyright.py [33ms[0m[32m                                                 [ 33%][0m
test/test_flake8.py [31mF[0m[31m                                                    [ 66%][0m
test/test_pep257.py [32m.[0m[31m                                                    [100%][0m

=================================== FAILURES ===================================
[31m[1m_________________________________ test_flake8 __________________________________[0m
[1m[31mtest/test_flake8.py[0m:23: in test_flake8
    [94massert[39;49;00m rc == [94m0[39;49;00m, \
[1m[31mE   AssertionError: Found 46 code style errors / warnings:[0m
[1m[31mE     ./setup.py:3:1: I201 Missing newline between import groups. 'from setuptools import find_packages, setup' is identified as Third Party and 'import os' is identified as Stdlib.[0m
[1m[31mE     ./plansys2_data_collector/csv_generator.py:2:2: W291 trailing whitespace[0m
[1m[31mE     ./plansys2_data_collector/csv_generator.py:6:2: W291 trailing whitespace[0m
[1m[31mE     ./plansys2_data_collector/csv_generator.py:8:2: W291 trailing whitespace[0m
[1m[31mE     ./plansys2_data_collector/csv_generator.py:17:1: F401 'rosbags.rosbag2.Reader' imported but unused[0m
[1m[31mE     ./plansys2_data_collector/csv_generator.py:18:1: I100 Import statements are in the wrong order. 'from rosbags.highlevel import AnyReader' should be before 'from rosbags.rosbag2 import Reader'[0m
[1m[31mE     ./plansys2_data_collector/csv_generator.py:21:1: I100 Import statements are in the wrong order. 'from pathlib import Path' should be before 'from rosbags.highlevel import AnyReader' and in a different group.[0m
[1m[31mE     ./plansys2_data_collector/csv_generator.py:39:100: E501 line too long (100 > 99 characters)[0m
[1m[31mE     ./plansys2_data_collector/csv_generator.py:46:1: W293 blank line contains whitespace[0m
[1m[31mE     ./plansys2_data_collector/csv_generator.py:48:100: E501 line too long (107 > 99 characters)[0m
[1m[31mE     ./plansys2_data_collector/csv_generator.py:74:1: E302 expected 2 blank lines, found 1[0m
[1m[31mE     ./plansys2_data_collector/csv_generator.py:76:5: F841 local variable 'node' is assigned to but never used[0m
[1m[31mE     ./plansys2_data_collector/csv_generator.py:82:1: E305 expected 2 blank lines after class or function definition, found 1[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:2:2: W291 trailing whitespace[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:6:2: W291 trailing whitespace[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:8:2: W291 trailing whitespace[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:17:1: I100 Import statements are in the wrong order. 'import pandas' should be before 'from rclpy.node import Node'[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:19:1: I100 Import statements are in the wrong order. 'import matplotlib.pyplot' should be before 'import seaborn'[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:20:1: I100 Import statements are in the wrong order. 'import sys' should be before 'import matplotlib.pyplot' and in a different group.[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:20:1: I201 Missing newline between import groups. 'import sys' is identified as Stdlib and 'import matplotlib.pyplot' is identified as Third Party.[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:21:1: I201 Missing newline between import groups. 'import numpy' is identified as Third Party and 'import sys' is identified as Stdlib.[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:23:1: E302 expected 2 blank lines, found 1[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:33:100: E501 line too long (102 > 99 characters)[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:43:29: Q000 Double quotes found but single quotes preferred[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:56:100: Q000 Double quotes found but single quotes preferred[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:56:100: E501 line too long (103 > 99 characters)[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:57:100: E501 line too long (105 > 99 characters)[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:57:102: Q000 Double quotes found but single quotes preferred[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:58:100: E501 line too long (107 > 99 characters)[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:58:104: Q000 Double quotes found but single quotes preferred[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:59:100: E501 line too long (105 > 99 characters)[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:59:102: Q000 Double quotes found but single quotes preferred[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:64:100: E501 line too long (104 > 99 characters)[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:67:100: E501 line too long (105 > 99 characters)[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:70:100: E501 line too long (108 > 99 characters)[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:73:100: E501 line too long (102 > 99 characters)[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:79:28: Q000 Double quotes found but single quotes preferred[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:85:1: E302 expected 2 blank lines, found 1[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:87:5: F841 local variable 'node' is assigned to but never used[0m
[1m[31mE     ./plansys2_data_collector/plot_generator.py:93:1: E305 expected 2 blank lines after class or function definition, found 1[0m
[1m[31mE     ./launch/plot.launch.py:49:1: W293 blank line contains whitespace[0m
[1m[31mE     ./launch/plot.launch.py:58:14: W292 no newline at end of file[0m
[1m[31mE     ./launch/generate_csv.launch.py:28:100: E501 line too long (101 > 99 characters)[0m
[1m[31mE     ./launch/generate_csv.launch.py:34:1: W293 blank line contains whitespace[0m
[1m[31mE     ./launch/generate_csv.launch.py:44:1: W293 blank line contains whitespace[0m
[1m[31mE     ./launch/generate_csv.launch.py:52:14: W292 no newline at end of file[0m
[1m[31mE   assert 1 == 0[0m
----------------------------- Captured stdout call -----------------------------

./setup.py:3:1: I201 Missing newline between import groups. 'from setuptools import find_packages, setup' is identified as Third Party and 'import os' is identified as Stdlib.
from setuptools import find_packages, setup
^

./plansys2_data_collector/csv_generator.py:2:2: W291 trailing whitespace
# 
 ^

./plansys2_data_collector/csv_generator.py:6:2: W291 trailing whitespace
# 
 ^

./plansys2_data_collector/csv_generator.py:8:2: W291 trailing whitespace
# 
 ^

./plansys2_data_collector/csv_generator.py:17:1: F401 'rosbags.rosbag2.Reader' imported but unused
from rosbags.rosbag2 import Reader
^

./plansys2_data_collector/csv_generator.py:18:1: I100 Import statements are in the wrong order. 'from rosbags.highlevel import AnyReader' should be before 'from rosbags.rosbag2 import Reader'
from rosbags.highlevel import AnyReader
^

./plansys2_data_collector/csv_generator.py:21:1: I100 Import statements are in the wrong order. 'from pathlib import Path' should be before 'from rosbags.highlevel import AnyReader' and in a different group.
from pathlib import Path
^

./plansys2_data_collector/csv_generator.py:39:100: E501 line too long (100 > 99 characters)
            self.get_logger().error('Both bag_file_path and csv_file_path parameters are required.')
                                                                                                   ^

./plansys2_data_collector/csv_generator.py:46:1: W293 blank line contains whitespace
        
^

./plansys2_data_collector/csv_generator.py:48:100: E501 line too long (107 > 99 characters)
            connections = [x for x in reader.connections if x.topic == '/action_execution_data_collection']
                                                                                                   ^

./plansys2_data_collector/csv_generator.py:74:1: E302 expected 2 blank lines, found 1
def main(args=None):
^

./plansys2_data_collector/csv_generator.py:76:5: F841 local variable 'node' is assigned to but never used
    node = BagToCsvNode()
    ^

./plansys2_data_collector/csv_generator.py:82:1: E305 expected 2 blank lines after class or function definition, found 1
if __name__ == '__main__':
^

./plansys2_data_collector/plot_generator.py:2:2: W291 trailing whitespace
# 
 ^

./plansys2_data_collector/plot_generator.py:6:2: W291 trailing whitespace
# 
 ^

./plansys2_data_collector/plot_generator.py:8:2: W291 trailing whitespace
# 
 ^

./plansys2_data_collector/plot_generator.py:17:1: I100 Import statements are in the wrong order. 'import pandas' should be before 'from rclpy.node import Node'
import pandas as pd
^

./plansys2_data_collector/plot_generator.py:19:1: I100 Import statements are in the wrong order. 'import matplotlib.pyplot' should be before 'import seaborn'
import matplotlib.pyplot as plt
^

./plansys2_data_collector/plot_generator.py:20:1: I100 Import statements are in the wrong order. 'import sys' should be before 'import matplotlib.pyplot' and in a different group.
import sys
^

./plansys2_data_collector/plot_generator.py:20:1: I201 Missing newline between import groups. 'import sys' is identified as Stdlib and 'import matplotlib.pyplot' is identified as Third Party.
import sys
^

./plansys2_data_collector/plot_generator.py:21:1: I201 Missing newline between import groups. 'import numpy' is identified as Third Party and 'import sys' is identified as Stdlib.
import numpy as np
^

./plansys2_data_collector/plot_generator.py:23:1: E302 expected 2 blank lines, found 1
class CsvToGraphNode(Node):
^

./plansys2_data_collector/plot_generator.py:33:100: E501 line too long (102 > 99 characters)
        plot_uncertainties = self.get_parameter('plot_uncertainties').get_parameter_value().bool_value
                                                                                                   ^

./plansys2_data_collector/plot_generator.py:43:29: Q000 Double quotes found but single quotes preferred
        sns.set_theme(style="whitegrid")
                            ^

./plansys2_data_collector/plot_generator.py:56:100: Q000 Double quotes found but single quotes preferred
                sns.lineplot(data=arg_df, x=x_axis, y='nominal_cost', label='Nominal Cost', marker="o")
                                                                                                   ^

./plansys2_data_collector/plot_generator.py:56:100: E501 line too long (103 > 99 characters)
                sns.lineplot(data=arg_df, x=x_axis, y='nominal_cost', label='Nominal Cost', marker="o")
                                                                                                   ^

./plansys2_data_collector/plot_generator.py:57:100: E501 line too long (105 > 99 characters)
                sns.lineplot(data=arg_df, x=x_axis, y='measured_cost', label='Measured Cost', marker="o")
                                                                                                   ^

./plansys2_data_collector/plot_generator.py:57:102: Q000 Double quotes found but single quotes preferred
                sns.lineplot(data=arg_df, x=x_axis, y='measured_cost', label='Measured Cost', marker="o")
                                                                                                     ^

./plansys2_data_collector/plot_generator.py:58:100: E501 line too long (107 > 99 characters)
                sns.lineplot(data=arg_df, x=x_axis, y='estimated_cost', label='Estimated Cost', marker="o")
                                                                                                   ^

./plansys2_data_collector/plot_generator.py:58:104: Q000 Double quotes found but single quotes preferred
                sns.lineplot(data=arg_df, x=x_axis, y='estimated_cost', label='Estimated Cost', marker="o")
                                                                                                       ^

./plansys2_data_collector/plot_generator.py:59:100: E501 line too long (105 > 99 characters)
                sns.lineplot(data=arg_df, x=x_axis, y='residual_cost', label='Residual Cost', marker="o")
                                                                                                   ^

[33m=============================== warnings summary ===============================[0m
test/test_flake8.py::test_flake8
test/test_flake8.py::test_flake8
  Warning: SelectableGroups dict interface is deprecated. Use select.

-- Docs: https://docs.pytest.org/en/stable/warnings.html
./plansys2_data_collector/plot_generator.py:59:102: Q000 Double quotes found but single quotes preferred
                sns.lineplot(data=arg_df, x=x_axis, y='residual_cost', label='Residual Cost', marker="o")
                                                                                                     ^

./plansys2_data_collector/plot_generator.py:64:100: E501 line too long (104 > 99 characters)
                                     arg_df['nominal_cost'] + arg_df['nominal_cost_std_dev'], alpha=0.3)
                                                                                                   ^

./plansys2_data_collector/plot_generator.py:67:100: E501 line too long (105 > 99 characters)
                                     arg_df['measured_cost'] + arg_df['mesured_cost_std_dev'], alpha=0.3)
                                                                                                   ^

./plansys2_data_collector/plot_generator.py:70:100: E501 line too long (108 > 99 characters)
                                     arg_df['estimated_cost'] + arg_df['estimated_cost_std_dev'], alpha=0.3)
                                                                                                   ^

./plansys2_data_collector/plot_generator.py:73:100: E501 line too long (102 > 99 characters)
                                     arg_df['residual_cost'] + arg_df['residual_cost_std'], alpha=0.3)
                                                                                                   ^

./plansys2_data_collector/plot_generator.py:79:28: Q000 Double quotes found but single quotes preferred
                plt_path = f"{output_dir}/node_{node_id}_arguments_{arg}.png"
                           ^

./plansys2_data_collector/plot_generator.py:85:1: E302 expected 2 blank lines, found 1
def main(args=None):
^

./plansys2_data_collector/plot_generator.py:87:5: F841 local variable 'node' is assigned to but never used
    node = CsvToGraphNode()
    ^

./plansys2_data_collector/plot_generator.py:93:1: E305 expected 2 blank lines after class or function definition, found 1
if __name__ == '__main__':
^

./launch/plot.launch.py:49:1: W293 blank line contains whitespace
    
^

./launch/plot.launch.py:58:14: W292 no newline at end of file
    return ld             ^

./launch/generate_csv.launch.py:28:100: E501 line too long (101 > 99 characters)
        default_value=pkg_dir + '/data/executions_data_first_test/executions_data_first_test_0.mcap',
                                                                                                   ^

./launch/generate_csv.launch.py:34:1: W293 blank line contains whitespace
    
^

./launch/generate_csv.launch.py:44:1: W293 blank line contains whitespace
    
^

./launch/generate_csv.launch.py:52:14: W292 no newline at end of file
    return ld             ^

3     E302 expected 2 blank lines, found 1
2     E305 expected 2 blank lines after class or function definition, found 1
12    E501 line too long (101 > 99 characters)
1     F401 'rosbags.rosbag2.Reader' imported but unused
2     F841 local variable 'node' is assigned to but never used
5     I100 Import statements are in the wrong order. 'from rosbags.highlevel import AnyReader' should be before 'from rosbags.rosbag2 import Reader'
3     I201 Missing newline between import groups. 'import sys' is identified as Stdlib and 'import matplotlib.pyplot' is identified as Third Party.
6     Q000 Double quotes found but single quotes preferred
6     W291 trailing whitespace
2     W292 no newline at end of file
4     W293 blank line contains whitespace

9 files checked
46 errors

'E'-type errors: 17
'F'-type errors: 3
'I'-type errors: 8
'Q'-type errors: 6
'W'-type errors: 12

Checked files:

* ./setup.py
* ./plansys2_data_collector/__init__.py
* ./plansys2_data_collector/csv_generator.py
* ./plansys2_data_collector/plot_generator.py
* ./test/test_pep257.py
* ./test/test_copyright.py
* ./test/test_flake8.py
* ./launch/plot.launch.py
* ./launch/generate_csv.launch.py
----------------------------- Captured stderr call -----------------------------
option --max-complexity: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
option --application-import-names: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
option --application-package-names: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
option --import-order-style: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
option --quotes: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
option --inline-quotes: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
option --multiline-quotes: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
option --docstring-quotes: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
- generated xml file: /home/kalman/plansys2_ws/src/plansys2_data_collector/build/plansys2_data_collector/pytest.xml -
=========================== short test summary info ============================
FAILED test/test_flake8.py::test_flake8 - AssertionError: Found 46 code style...
[31m============== [31m[1m1 failed[0m, [32m1 passed[0m, [33m1 skipped[0m, [33m2 warnings[0m[31m in 0.35s[0m[31m ==============[0m
